/* global window */

// Practice question bank (add more freely).
// Schema:
// { id: string, tag: "technical"|"quant"|"reasoning"|"english"|"gk"|"iffco", prompt: string, options: string[4], answerIndex: 0..3 }

window.IffcoQuestionBank = [
  // --------------------
  // TECHNICAL (CS CORE)
  // --------------------
  {
    id: "tech_dbms_001",
    tag: "technical",
    prompt: "Which normal form removes partial dependency?",
    options: ["1NF", "2NF", "3NF", "BCNF"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_002",
    tag: "technical",
    prompt: "In SQL, which clause is used to filter groups after aggregation?",
    options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_003",
    tag: "technical",
    prompt: "Which isolation level prevents dirty reads but may allow non-repeatable reads?",
    options: ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_004",
    tag: "technical",
    prompt: "Which index is typically best for range queries on an ordered key?",
    options: ["Hash index", "B-Tree index", "Bitmap index", "Full table scan"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_005",
    tag: "technical",
    prompt: "Which join returns rows that have matching values in both tables?",
    options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
    answerIndex: 0,
  },
  {
    id: "tech_dbms_006",
    tag: "technical",
    prompt: "In SQL, comparison with NULL using '=' results in:",
    options: ["TRUE", "FALSE", "UNKNOWN", "ERROR"],
    answerIndex: 2,
  },
  {
    id: "tech_dbms_007",
    tag: "technical",
    prompt: "Which of these is a DDL command?",
    options: ["INSERT", "UPDATE", "CREATE", "SELECT"],
    answerIndex: 2,
  },
  {
    id: "tech_dbms_008",
    tag: "technical",
    prompt: "In a relational table, a foreign key primarily enforces:",
    options: ["Uniqueness", "Referential integrity", "Atomicity", "Durability"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_009",
    tag: "technical",
    prompt: "Which is NOT an ACID property?",
    options: ["Atomicity", "Consistency", "Isolation", "Availability"],
    answerIndex: 3,
  },
  {
    id: "tech_dbms_010",
    tag: "technical",
    prompt: "Which anomaly is prevented by normalization?",
    options: ["Insertion anomaly", "Update anomaly", "Deletion anomaly", "All of the above"],
    answerIndex: 3,
  },
  {
    id: "tech_dbms_011",
    tag: "technical",
    prompt: "A primary key in a table must be:",
    options: ["Unique and NOT NULL", "NOT NULL but can repeat", "Unique but can be NULL", "Neither unique nor NOT NULL"],
    answerIndex: 0,
  },
  {
    id: "tech_dbms_012",
    tag: "technical",
    prompt: "Which schedule is conflict-serializable?",
    options: ["If precedence graph has a cycle", "If precedence graph is acyclic", "If all transactions are read-only", "If all transactions are write-only"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_013",
    tag: "technical",
    prompt: "In two-phase locking (2PL), the rule is:",
    options: [
      "Locks can be acquired after releasing any lock",
      "All locks must be released before acquiring any lock",
      "No lock is acquired after the first lock is released",
      "Locks are never released",
    ],
    answerIndex: 2,
  },
  {
    id: "tech_dbms_014",
    tag: "technical",
    prompt: "Which of the following is a non-clustered index characteristic?",
    options: [
      "Data rows are stored in the index order",
      "Only one per table is allowed",
      "Index contains pointers to data rows stored elsewhere",
      "Always faster than clustered index",
    ],
    answerIndex: 2,
  },
  {
    id: "tech_dbms_015",
    tag: "technical",
    prompt: "A transaction is said to be durable if:",
    options: [
      "It never reads uncommitted data",
      "Its effects persist even after a system crash",
      "It always runs alone",
      "It completes in constant time",
    ],
    answerIndex: 1,
  },

  {
    id: "tech_os_001",
    tag: "technical",
    prompt: "Which of the following is NOT a process state?",
    options: ["New", "Ready", "Running", "Compiled"],
    answerIndex: 3,
  },
  {
    id: "tech_os_002",
    tag: "technical",
    prompt: "A context switch occurs when:",
    options: [
      "CPU changes from user mode to kernel mode",
      "CPU switches from one process/thread to another",
      "A process allocates memory",
      "A file is opened",
    ],
    answerIndex: 1,
  },
  {
    id: "tech_os_003",
    tag: "technical",
    prompt: "Which CPU scheduling algorithm may cause starvation?",
    options: ["FCFS", "SJF", "Round Robin", "FIFO paging"],
    answerIndex: 1,
  },
  {
    id: "tech_os_004",
    tag: "technical",
    prompt: "Deadlock requires which condition?",
    options: ["Mutual exclusion", "Preemption", "Single process", "Infinite memory"],
    answerIndex: 0,
  },
  {
    id: "tech_os_005",
    tag: "technical",
    prompt: "A semaphore is primarily used for:",
    options: ["Scheduling compilation", "Synchronization", "Encryption", "Sorting"],
    answerIndex: 1,
  },
  {
    id: "tech_os_006",
    tag: "technical",
    prompt: "Paging helps to eliminate:",
    options: ["External fragmentation", "Internal fragmentation", "Deadlock", "CPU starvation"],
    answerIndex: 0,
  },
  {
    id: "tech_os_007",
    tag: "technical",
    prompt: "Which memory allocation strategy selects the smallest block that fits?",
    options: ["First fit", "Best fit", "Worst fit", "Random fit"],
    answerIndex: 1,
  },
  {
    id: "tech_os_008",
    tag: "technical",
    prompt: "A page fault happens when:",
    options: ["Page is in cache", "Page is not in main memory", "CPU is idle", "Disk is full"],
    answerIndex: 1,
  },
  {
    id: "tech_os_009",
    tag: "technical",
    prompt: "Which is true about threads vs processes?",
    options: [
      "Threads have separate address spaces within a process",
      "Threads within a process share the same address space",
      "Processes share the same stack by default",
      "Threads cannot run in parallel",
    ],
    answerIndex: 1,
  },
  {
    id: "tech_os_010",
    tag: "technical",
    prompt: "Which is a non-preemptive scheduling algorithm?",
    options: ["Round Robin", "Preemptive Priority", "FCFS", "SRTF"],
    answerIndex: 2,
  },

  {
    id: "tech_cn_001",
    tag: "technical",
    prompt: "TCP is primarily:",
    options: ["Connectionless and unreliable", "Connection-oriented and reliable", "Connectionless and reliable", "Connection-oriented and unreliable"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_002",
    tag: "technical",
    prompt: "How many steps are there in TCP 3-way handshake?",
    options: ["2", "3", "4", "5"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_003",
    tag: "technical",
    prompt: "DNS primarily maps:",
    options: ["IP to MAC", "Domain name to IP", "MAC to port", "Port to process ID"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_004",
    tag: "technical",
    prompt: "HTTPS is HTTP over:",
    options: ["FTP", "TLS/SSL", "UDP only", "SMTP"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_005",
    tag: "technical",
    prompt: "Default port for HTTP is:",
    options: ["21", "22", "80", "443"],
    answerIndex: 2,
  },
  {
    id: "tech_cn_006",
    tag: "technical",
    prompt: "Default port for HTTPS is:",
    options: ["53", "80", "110", "443"],
    answerIndex: 3,
  },
  {
    id: "tech_cn_007",
    tag: "technical",
    prompt: "Which device works at the Network layer (Layer 3) in OSI model?",
    options: ["Hub", "Switch", "Router", "Repeater"],
    answerIndex: 2,
  },
  {
    id: "tech_cn_008",
    tag: "technical",
    prompt: "Which layer is responsible for end-to-end delivery and reliability in OSI?",
    options: ["Data Link", "Network", "Transport", "Session"],
    answerIndex: 2,
  },
  {
    id: "tech_cn_009",
    tag: "technical",
    prompt: "NAT is used mainly to:",
    options: ["Increase CPU speed", "Translate private IPs to public IP", "Encrypt DNS", "Compress TCP packets"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_010",
    tag: "technical",
    prompt: "Which protocol is used to obtain an IP address automatically?",
    options: ["HTTP", "DHCP", "FTP", "ARP"],
    answerIndex: 1,
  },

  {
    id: "tech_dsa_001",
    tag: "technical",
    prompt: "Time complexity of binary search on a sorted array is:",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_002",
    tag: "technical",
    prompt: "Which data structure is used in BFS traversal?",
    options: ["Stack", "Queue", "Heap", "HashMap"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_003",
    tag: "technical",
    prompt: "Which data structure is used in DFS (iterative) traversal?",
    options: ["Stack", "Queue", "Trie", "Deque only"],
    answerIndex: 0,
  },
  {
    id: "tech_dsa_004",
    tag: "technical",
    prompt: "In a max-heap, the largest element is at:",
    options: ["Any leaf", "The root", "The last node", "Middle level"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_005",
    tag: "technical",
    prompt: "Worst-case time complexity of quicksort is:",
    options: ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"],
    answerIndex: 2,
  },
  {
    id: "tech_dsa_006",
    tag: "technical",
    prompt: "Which sorting algorithm is stable by default?",
    options: ["Quick sort", "Heap sort", "Merge sort", "Selection sort"],
    answerIndex: 2,
  },
  {
    id: "tech_dsa_007",
    tag: "technical",
    prompt: "A hash collision occurs when:",
    options: [
      "Two different keys map to the same hash index",
      "A key maps to an empty bucket",
      "Hash function returns negative values",
      "Table is empty",
    ],
    answerIndex: 0,
  },
  {
    id: "tech_dsa_008",
    tag: "technical",
    prompt: "Which traversal of BST gives sorted order of elements?",
    options: ["Preorder", "Inorder", "Postorder", "Level order"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_009",
    tag: "technical",
    prompt: "Time complexity of inserting into a balanced BST is:",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_010",
    tag: "technical",
    prompt: "Which graph algorithm finds shortest paths from a single source (non-negative weights)?",
    options: ["Prim", "Kruskal", "Dijkstra", "Floyd-Warshall"],
    answerIndex: 2,
  },
  {
    id: "tech_dsa_011",
    tag: "technical",
    prompt: "Floyd-Warshall algorithm computes:",
    options: ["MST", "All-pairs shortest paths", "Topological order", "Strongly connected components"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_012",
    tag: "technical",
    prompt: "Topological sorting is possible only in:",
    options: ["Undirected graphs", "DAG", "Complete graphs", "Graphs with cycles"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_013",
    tag: "technical",
    prompt: "Which data structure supports LIFO?",
    options: ["Queue", "Stack", "ArrayList", "Binary tree"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_014",
    tag: "technical",
    prompt: "In Big-O notation, dropping constants means:",
    options: ["O(2n) equals O(n)", "O(n) equals O(n^2)", "O(log n) equals O(n)", "O(1) equals O(n)"],
    answerIndex: 0,
  },
  {
    id: "tech_dsa_015",
    tag: "technical",
    prompt: "Which algorithm is used to find MST?",
    options: ["Dijkstra", "Bellman-Ford", "Kruskal", "Floyd-Warshall"],
    answerIndex: 2,
  },
  {
    id: "tech_dsa_016",
    tag: "technical",
    prompt: "A queue implemented using an array with front/rear requires what to avoid wasted space?",
    options: ["Recursion", "Circular queue", "Binary search", "Hashing"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_017",
    tag: "technical",
    prompt: "Which data structure is best suited for prefix searches (like autocomplete)?",
    options: ["Heap", "Trie", "Stack", "Graph"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_018",
    tag: "technical",
    prompt: "In a linked list, insertion at head is:",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 0,
  },
  {
    id: "tech_dsa_019",
    tag: "technical",
    prompt: "Which algorithm is used for cycle detection in directed graphs using colors/recursion stack?",
    options: ["Binary search", "DFS", "Counting sort", "Heapify"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_020",
    tag: "technical",
    prompt: "Which algorithm uses divide-and-conquer?",
    options: ["Merge sort", "Insertion sort", "Bubble sort", "Linear search"],
    answerIndex: 0,
  },

  {
    id: "tech_java_001",
    tag: "technical",
    prompt: "JVM stands for:",
    options: ["Java Visual Model", "Java Virtual Machine", "Java Variable Manager", "Just Virtual Memory"],
    answerIndex: 1,
  },
  {
    id: "tech_java_002",
    tag: "technical",
    prompt: "JDK contains:",
    options: ["Only JVM", "Only JRE", "JRE + development tools", "Only compiler"],
    answerIndex: 2,
  },
  {
    id: "tech_java_003",
    tag: "technical",
    prompt: "Which keyword prevents a method from being overridden?",
    options: ["static", "final", "abstract", "volatile"],
    answerIndex: 1,
  },
  {
    id: "tech_java_004",
    tag: "technical",
    prompt: "Which collection does NOT allow duplicates?",
    options: ["List", "Set", "ArrayList", "LinkedList"],
    answerIndex: 1,
  },
  {
    id: "tech_java_005",
    tag: "technical",
    prompt: "Which is true about an interface in Java?",
    options: [
      "It can have instance fields with state",
      "A class can implement multiple interfaces",
      "Interfaces cannot have methods",
      "Interfaces cannot be used for polymorphism",
    ],
    answerIndex: 1,
  },
  {
    id: "tech_java_006",
    tag: "technical",
    prompt: "Which exception is unchecked?",
    options: ["IOException", "SQLException", "NullPointerException", "ClassNotFoundException"],
    answerIndex: 2,
  },
  {
    id: "tech_java_007",
    tag: "technical",
    prompt: "Which keyword is used to inherit a class?",
    options: ["this", "super", "extends", "implements"],
    answerIndex: 2,
  },
  {
    id: "tech_java_008",
    tag: "technical",
    prompt: "Overloading means:",
    options: [
      "Same method name with different parameter list",
      "Same method name with same parameters but different return type",
      "Same class name used twice",
      "Changing variable values at runtime",
    ],
    answerIndex: 0,
  },
  {
    id: "tech_java_009",
    tag: "technical",
    prompt: "Which is a valid way to create a thread in Java?",
    options: [
      "Implement Runnable or extend Thread",
      "Only extend Object",
      "Only use reflection",
      "Only use enum",
    ],
    answerIndex: 0,
  },
  {
    id: "tech_java_010",
    tag: "technical",
    prompt: "Which modifier makes a variable visible only within the same class?",
    options: ["public", "protected", "private", "default (package-private)"],
    answerIndex: 2,
  },

  {
    id: "tech_misc_001",
    tag: "technical",
    prompt: "REST typically uses which protocol?",
    options: ["HTTP", "FTP", "SMTP", "SNMP"],
    answerIndex: 0,
  },
  {
    id: "tech_misc_002",
    tag: "technical",
    prompt: "HTTP method generally used to update an existing resource is:",
    options: ["GET", "POST", "PUT", "TRACE"],
    answerIndex: 2,
  },
  {
    id: "tech_misc_003",
    tag: "technical",
    prompt: "Which HTTP status code means 'Not Found'?",
    options: ["200", "301", "404", "500"],
    answerIndex: 2,
  },
  {
    id: "tech_misc_004",
    tag: "technical",
    prompt: "Which data structure is best for O(1) average lookups by key?",
    options: ["Array", "Hash table", "Binary search tree", "Linked list"],
    answerIndex: 1,
  },
  {
    id: "tech_misc_005",
    tag: "technical",
    prompt: "In SQL, which constraint ensures unique values in a column (can allow NULLs depending on DB)?",
    options: ["CHECK", "UNIQUE", "FOREIGN KEY", "DEFAULT"],
    answerIndex: 1,
  },
  {
    id: "tech_misc_006",
    tag: "technical",
    prompt: "Which is an example of symmetric encryption?",
    options: ["AES", "RSA", "DSA", "ECC"],
    answerIndex: 0,
  },
  {
    id: "tech_misc_007",
    tag: "technical",
    prompt: "Which layer in TCP/IP model corresponds to OSI Transport layer?",
    options: ["Application", "Transport", "Internet", "Link"],
    answerIndex: 1,
  },
  {
    id: "tech_misc_008",
    tag: "technical",
    prompt: "A race condition occurs when:",
    options: [
      "Two threads access shared data without proper synchronization",
      "CPU is faster than memory",
      "Disk is slow",
      "A program compiles twice",
    ],
    answerIndex: 0,
  },
  {
    id: "tech_misc_009",
    tag: "technical",
    prompt: "Which of these is a NoSQL database type?",
    options: ["Relational", "Document store", "Normalization", "BCNF"],
    answerIndex: 1,
  },
  {
    id: "tech_misc_010",
    tag: "technical",
    prompt: "CAP theorem says a distributed system can provide at most two of:",
    options: [
      "Consistency, Availability, Partition tolerance",
      "Concurrency, Accuracy, Performance",
      "Caching, Availability, Persistence",
      "Correctness, Atomicity, Privacy",
    ],
    answerIndex: 0,
  },

  // --------------------
  // QUANT (10)
  // --------------------
  {
    id: "quant_001",
    tag: "quant",
    prompt: "If 6 pens cost ₹90, what is the cost of 10 pens?",
    options: ["₹120", "₹130", "₹140", "₹150"],
    answerIndex: 0,
  },
  {
    id: "quant_002",
    tag: "quant",
    prompt: "A train covers 180 km in 3 hours. Speed = ?",
    options: ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
    answerIndex: 2,
  },
  {
    id: "quant_003",
    tag: "quant",
    prompt: "20% of 250 is:",
    options: ["25", "40", "50", "60"],
    answerIndex: 2,
  },
  {
    id: "quant_004",
    tag: "quant",
    prompt: "If A:B = 2:3 and B:C = 4:5, then A:C = ?",
    options: ["8:15", "2:5", "4:9", "6:10"],
    answerIndex: 0,
  },
  {
    id: "quant_005",
    tag: "quant",
    prompt: "Simple interest on ₹1000 at 10% per annum for 2 years is:",
    options: ["₹100", "₹150", "₹200", "₹250"],
    answerIndex: 2,
  },
  {
    id: "quant_006",
    tag: "quant",
    prompt: "LCM of 6 and 8 is:",
    options: ["12", "18", "24", "48"],
    answerIndex: 2,
  },
  {
    id: "quant_007",
    tag: "quant",
    prompt: "If x + 5 = 17, x = ?",
    options: ["10", "11", "12", "13"],
    answerIndex: 2,
  },
  {
    id: "quant_008",
    tag: "quant",
    prompt: "A shop gives 10% discount on ₹500. Selling price = ?",
    options: ["₹450", "₹460", "₹470", "₹480"],
    answerIndex: 0,
  },
  {
    id: "quant_009",
    tag: "quant",
    prompt: "If 5 workers finish a job in 12 days, how many days for 10 workers (same rate)?",
    options: ["3", "5", "6", "8"],
    answerIndex: 2,
  },
  {
    id: "quant_010",
    tag: "quant",
    prompt: "Which is larger?",
    options: ["0.8", "0.08", "0.808", "0.88"],
    answerIndex: 3,
  },

  // --------------------
  // REASONING (10)
  // --------------------
  {
    id: "reason_001",
    tag: "reasoning",
    prompt: "Find the odd one out: 2, 3, 5, 9, 11",
    options: ["2", "3", "5", "9"],
    answerIndex: 3,
  },
  {
    id: "reason_002",
    tag: "reasoning",
    prompt: "If SOUTH is coded as T P V U I, then NORTH is coded as:",
    options: ["O P S U I", "O Q S U I", "O P R U I", "O P S V I"],
    answerIndex: 0,
  },
  {
    id: "reason_003",
    tag: "reasoning",
    prompt: "Complete the series: A, C, F, J, O, ?",
    options: ["T", "U", "V", "W"],
    answerIndex: 1,
  },
  {
    id: "reason_004",
    tag: "reasoning",
    prompt: "In a certain code, CAT = 24. Then DOG = ? (A=1, B=2...)",
    options: ["26", "28", "30", "32"],
    answerIndex: 0,
  },
  {
    id: "reason_005",
    tag: "reasoning",
    prompt: "Find the next number: 1, 4, 9, 16, ?",
    options: ["20", "24", "25", "36"],
    answerIndex: 2,
  },
  {
    id: "reason_006",
    tag: "reasoning",
    prompt: "If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are:",
    options: ["Lazzies", "Not Lazzies", "Some Lazzies", "Cannot be determined"],
    answerIndex: 0,
  },
  {
    id: "reason_007",
    tag: "reasoning",
    prompt: "Find the missing term: 5, 11, 23, 47, ?",
    options: ["93", "94", "95", "96"],
    answerIndex: 2,
  },
  {
    id: "reason_008",
    tag: "reasoning",
    prompt: "If 2 + 3 = 13 and 3 + 4 = 25, then 4 + 5 = ? (pattern: a^2 + b^2)",
    options: ["41", "39", "37", "43"],
    answerIndex: 0,
  },
  {
    id: "reason_009",
    tag: "reasoning",
    prompt: "Choose the correct mirror image of 'E'.",
    options: ["Ǝ", "E", "∃", "Σ"],
    answerIndex: 0,
  },
  {
    id: "reason_010",
    tag: "reasoning",
    prompt: "If today is Monday, what day will it be after 45 days?",
    options: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    answerIndex: 3,
  },

  // --------------------
  // ENGLISH (10)
  // --------------------
  {
    id: "eng_001",
    tag: "english",
    prompt: "Choose the correct spelling:",
    options: ["Accomodate", "Acommodate", "Accommodate", "Acomodate"],
    answerIndex: 2,
  },
  {
    id: "eng_002",
    tag: "english",
    prompt: "Synonym of 'rapid' is:",
    options: ["Slow", "Quick", "Late", "Weak"],
    answerIndex: 1,
  },
  {
    id: "eng_003",
    tag: "english",
    prompt: "Antonym of 'increase' is:",
    options: ["Expand", "Enhance", "Decrease", "Add"],
    answerIndex: 2,
  },
  {
    id: "eng_004",
    tag: "english",
    prompt: "Choose the correct sentence:",
    options: [
      "He don't like coffee.",
      "He doesn't like coffee.",
      "He doesn't likes coffee.",
      "He not likes coffee.",
    ],
    answerIndex: 1,
  },
  {
    id: "eng_005",
    tag: "english",
    prompt: "Fill in the blank: She ___ to office every day.",
    options: ["go", "goes", "gone", "going"],
    answerIndex: 1,
  },
  {
    id: "eng_006",
    tag: "english",
    prompt: "Choose the correct passive voice: 'They completed the work.'",
    options: [
      "The work has completed by them.",
      "The work was completed by them.",
      "The work is completed by them.",
      "The work had complete by them.",
    ],
    answerIndex: 1,
  },
  {
    id: "eng_007",
    tag: "english",
    prompt: "One word for 'able to use both hands equally well':",
    options: ["Ambidextrous", "Ambiguous", "Amicable", "Amorphous"],
    answerIndex: 0,
  },
  {
    id: "eng_008",
    tag: "english",
    prompt: "Choose the correct article: He is ___ honest man.",
    options: ["a", "an", "the", "no article"],
    answerIndex: 1,
  },
  {
    id: "eng_009",
    tag: "english",
    prompt: "Meaning of 'brevity' is:",
    options: ["Length", "Shortness", "Anger", "Clarity"],
    answerIndex: 1,
  },
  {
    id: "eng_010",
    tag: "english",
    prompt: "Choose the correct preposition: He is good ___ math.",
    options: ["in", "on", "at", "by"],
    answerIndex: 2,
  },

  // --------------------
  // GK (10)
  // --------------------
  {
    id: "gk_001",
    tag: "gk",
    prompt: "The Constitution of India came into effect on:",
    options: ["15 Aug 1947", "26 Jan 1950", "2 Oct 1949", "26 Nov 1949"],
    answerIndex: 1,
  },
  {
    id: "gk_002",
    tag: "gk",
    prompt: "The currency of Japan is:",
    options: ["Yen", "Won", "Dollar", "Peso"],
    answerIndex: 0,
  },
  {
    id: "gk_003",
    tag: "gk",
    prompt: "Which planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Jupiter", "Venus"],
    answerIndex: 1,
  },
  {
    id: "gk_004",
    tag: "gk",
    prompt: "The national animal of India is:",
    options: ["Lion", "Tiger", "Elephant", "Leopard"],
    answerIndex: 1,
  },
  {
    id: "gk_005",
    tag: "gk",
    prompt: "The largest ocean is:",
    options: ["Indian", "Arctic", "Atlantic", "Pacific"],
    answerIndex: 3,
  },
  {
    id: "gk_006",
    tag: "gk",
    prompt: "Which gas is most abundant in Earth's atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    answerIndex: 1,
  },
  {
    id: "gk_007",
    tag: "gk",
    prompt: "The SI unit of electric current is:",
    options: ["Volt", "Watt", "Ampere", "Ohm"],
    answerIndex: 2,
  },
  {
    id: "gk_008",
    tag: "gk",
    prompt: "Which is the largest continent by area?",
    options: ["Africa", "Asia", "Europe", "Antarctica"],
    answerIndex: 1,
  },
  {
    id: "gk_009",
    tag: "gk",
    prompt: "The headquarters of the United Nations is in:",
    options: ["Geneva", "New York", "Paris", "London"],
    answerIndex: 1,
  },
  {
    id: "gk_010",
    tag: "gk",
    prompt: "Which instrument is used to measure atmospheric pressure?",
    options: ["Thermometer", "Barometer", "Hygrometer", "Anemometer"],
    answerIndex: 1,
  },

  // --------------------
  // IFFCO (10) — from official sources (annual report + production units page)
  // --------------------
  {
    id: "iffco_001",
    tag: "iffco",
    prompt: "IFFCO stands for:",
    options: [
      "Indian Farmers Finance Cooperative Ltd.",
      "Indian Farmers Fertiliser Cooperative Limited",
      "Indian Federation of Fertiliser Companies",
      "Indian Fertiliser Funding Corporation",
    ],
    answerIndex: 1,
  },
  {
    id: "iffco_002",
    tag: "iffco",
    prompt: "IFFCO (Indian Farmers Fertiliser Cooperative Ltd.) was established on:",
    options: ["3 Nov 1967", "15 Aug 1947", "26 Jan 1950", "1 Apr 1974"],
    answerIndex: 0,
  },
  {
    id: "iffco_003",
    tag: "iffco",
    prompt: "IFFCO Head Office is in:",
    options: ["Mumbai", "New Delhi", "Kolkata", "Chennai"],
    answerIndex: 1,
  },
  {
    id: "iffco_004",
    tag: "iffco",
    prompt: "IFFCO is primarily a:",
    options: ["Private company", "Multi-State Cooperative Society", "State government department", "Foreign MNC subsidiary"],
    answerIndex: 1,
  },
  {
    id: "iffco_005",
    tag: "iffco",
    prompt: "How many major IFFCO production units are listed on the official site?",
    options: ["3", "4", "5", "6"],
    answerIndex: 2,
  },
  {
    id: "iffco_006",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Kalol", "Pune", "Jaipur", "Bhopal"],
    answerIndex: 0,
  },
  {
    id: "iffco_007",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Aonla", "Surat", "Indore", "Noida"],
    answerIndex: 0,
  },
  {
    id: "iffco_008",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Paradeep", "Ranchi", "Guwahati", "Agra"],
    answerIndex: 0,
  },
  {
    id: "iffco_009",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Kandla", "Varanasi", "Nagpur", "Chandigarh"],
    answerIndex: 0,
  },
  {
    id: "iffco_010",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Phulpur", "Lucknow", "Hyderabad", "Patna"],
    answerIndex: 0,
  },
];

