/* global window */

// Practice question bank (add more freely).
// Schema:
// { id: string, tag: "technical"|"quant"|"reasoning"|"english"|"gk"|"iffco", prompt: string, options: string[4], answerIndex: 0..3 }

window.IffcoQuestionBank = [
  // --------------------
  // TECHNICAL (CS CORE)
  // --------------------
  {
    id: "tech_dbms_001",
    tag: "technical",
    prompt: "Which normal form removes partial dependency?",
    options: ["1NF", "2NF", "3NF", "BCNF"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_002",
    tag: "technical",
    prompt: "In SQL, which clause is used to filter groups after aggregation?",
    options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_003",
    tag: "technical",
    prompt: "Which isolation level prevents dirty reads but may allow non-repeatable reads?",
    options: ["Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_004",
    tag: "technical",
    prompt: "Which index is typically best for range queries on an ordered key?",
    options: ["Hash index", "B-Tree index", "Bitmap index", "Full table scan"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_005",
    tag: "technical",
    prompt: "Which join returns rows that have matching values in both tables?",
    options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"],
    answerIndex: 0,
  },
  {
    id: "tech_dbms_006",
    tag: "technical",
    prompt: "In SQL, comparison with NULL using '=' results in:",
    options: ["TRUE", "FALSE", "UNKNOWN", "ERROR"],
    answerIndex: 2,
  },
  {
    id: "tech_dbms_007",
    tag: "technical",
    prompt: "Which of these is a DDL command?",
    options: ["INSERT", "UPDATE", "CREATE", "SELECT"],
    answerIndex: 2,
  },
  {
    id: "tech_dbms_008",
    tag: "technical",
    prompt: "In a relational table, a foreign key primarily enforces:",
    options: ["Uniqueness", "Referential integrity", "Atomicity", "Durability"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_009",
    tag: "technical",
    prompt: "Which is NOT an ACID property?",
    options: ["Atomicity", "Consistency", "Isolation", "Availability"],
    answerIndex: 3,
  },
  {
    id: "tech_dbms_010",
    tag: "technical",
    prompt: "Which anomaly is prevented by normalization?",
    options: ["Insertion anomaly", "Update anomaly", "Deletion anomaly", "All of the above"],
    answerIndex: 3,
  },
  {
    id: "tech_dbms_011",
    tag: "technical",
    prompt: "A primary key in a table must be:",
    options: ["Unique and NOT NULL", "NOT NULL but can repeat", "Unique but can be NULL", "Neither unique nor NOT NULL"],
    answerIndex: 0,
  },
  {
    id: "tech_dbms_012",
    tag: "technical",
    prompt: "Which schedule is conflict-serializable?",
    options: ["If precedence graph has a cycle", "If precedence graph is acyclic", "If all transactions are read-only", "If all transactions are write-only"],
    answerIndex: 1,
  },
  {
    id: "tech_dbms_013",
    tag: "technical",
    prompt: "In two-phase locking (2PL), the rule is:",
    options: [
      "Locks can be acquired after releasing any lock",
      "All locks must be released before acquiring any lock",
      "No lock is acquired after the first lock is released",
      "Locks are never released",
    ],
    answerIndex: 2,
  },
  {
    id: "tech_dbms_014",
    tag: "technical",
    prompt: "Which of the following is a non-clustered index characteristic?",
    options: [
      "Data rows are stored in the index order",
      "Only one per table is allowed",
      "Index contains pointers to data rows stored elsewhere",
      "Always faster than clustered index",
    ],
    answerIndex: 2,
  },
  {
    id: "tech_dbms_015",
    tag: "technical",
    prompt: "A transaction is said to be durable if:",
    options: [
      "It never reads uncommitted data",
      "Its effects persist even after a system crash",
      "It always runs alone",
      "It completes in constant time",
    ],
    answerIndex: 1,
  },

  {
    id: "tech_os_001",
    tag: "technical",
    prompt: "Which of the following is NOT a process state?",
    options: ["New", "Ready", "Running", "Compiled"],
    answerIndex: 3,
  },
  {
    id: "tech_os_002",
    tag: "technical",
    prompt: "A context switch occurs when:",
    options: [
      "CPU changes from user mode to kernel mode",
      "CPU switches from one process/thread to another",
      "A process allocates memory",
      "A file is opened",
    ],
    answerIndex: 1,
  },
  {
    id: "tech_os_003",
    tag: "technical",
    prompt: "Which CPU scheduling algorithm may cause starvation?",
    options: ["FCFS", "SJF", "Round Robin", "FIFO paging"],
    answerIndex: 1,
  },
  {
    id: "tech_os_004",
    tag: "technical",
    prompt: "Deadlock requires which condition?",
    options: ["Mutual exclusion", "Preemption", "Single process", "Infinite memory"],
    answerIndex: 0,
  },
  {
    id: "tech_os_005",
    tag: "technical",
    prompt: "A semaphore is primarily used for:",
    options: ["Scheduling compilation", "Synchronization", "Encryption", "Sorting"],
    answerIndex: 1,
  },
  {
    id: "tech_os_006",
    tag: "technical",
    prompt: "Paging helps to eliminate:",
    options: ["External fragmentation", "Internal fragmentation", "Deadlock", "CPU starvation"],
    answerIndex: 0,
  },
  {
    id: "tech_os_007",
    tag: "technical",
    prompt: "Which memory allocation strategy selects the smallest block that fits?",
    options: ["First fit", "Best fit", "Worst fit", "Random fit"],
    answerIndex: 1,
  },
  {
    id: "tech_os_008",
    tag: "technical",
    prompt: "A page fault happens when:",
    options: ["Page is in cache", "Page is not in main memory", "CPU is idle", "Disk is full"],
    answerIndex: 1,
  },
  {
    id: "tech_os_009",
    tag: "technical",
    prompt: "Which is true about threads vs processes?",
    options: [
      "Threads have separate address spaces within a process",
      "Threads within a process share the same address space",
      "Processes share the same stack by default",
      "Threads cannot run in parallel",
    ],
    answerIndex: 1,
  },
  {
    id: "tech_os_010",
    tag: "technical",
    prompt: "Which is a non-preemptive scheduling algorithm?",
    options: ["Round Robin", "Preemptive Priority", "FCFS", "SRTF"],
    answerIndex: 2,
  },

  {
    id: "tech_cn_001",
    tag: "technical",
    prompt: "TCP is primarily:",
    options: ["Connectionless and unreliable", "Connection-oriented and reliable", "Connectionless and reliable", "Connection-oriented and unreliable"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_002",
    tag: "technical",
    prompt: "How many steps are there in TCP 3-way handshake?",
    options: ["2", "3", "4", "5"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_003",
    tag: "technical",
    prompt: "DNS primarily maps:",
    options: ["IP to MAC", "Domain name to IP", "MAC to port", "Port to process ID"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_004",
    tag: "technical",
    prompt: "HTTPS is HTTP over:",
    options: ["FTP", "TLS/SSL", "UDP only", "SMTP"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_005",
    tag: "technical",
    prompt: "Default port for HTTP is:",
    options: ["21", "22", "80", "443"],
    answerIndex: 2,
  },
  {
    id: "tech_cn_006",
    tag: "technical",
    prompt: "Default port for HTTPS is:",
    options: ["53", "80", "110", "443"],
    answerIndex: 3,
  },
  {
    id: "tech_cn_007",
    tag: "technical",
    prompt: "Which device works at the Network layer (Layer 3) in OSI model?",
    options: ["Hub", "Switch", "Router", "Repeater"],
    answerIndex: 2,
  },
  {
    id: "tech_cn_008",
    tag: "technical",
    prompt: "Which layer is responsible for end-to-end delivery and reliability in OSI?",
    options: ["Data Link", "Network", "Transport", "Session"],
    answerIndex: 2,
  },
  {
    id: "tech_cn_009",
    tag: "technical",
    prompt: "NAT is used mainly to:",
    options: ["Increase CPU speed", "Translate private IPs to public IP", "Encrypt DNS", "Compress TCP packets"],
    answerIndex: 1,
  },
  {
    id: "tech_cn_010",
    tag: "technical",
    prompt: "Which protocol is used to obtain an IP address automatically?",
    options: ["HTTP", "DHCP", "FTP", "ARP"],
    answerIndex: 1,
  },

  {
    id: "tech_dsa_001",
    tag: "technical",
    prompt: "Time complexity of binary search on a sorted array is:",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_002",
    tag: "technical",
    prompt: "Which data structure is used in BFS traversal?",
    options: ["Stack", "Queue", "Heap", "HashMap"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_003",
    tag: "technical",
    prompt: "Which data structure is used in DFS (iterative) traversal?",
    options: ["Stack", "Queue", "Trie", "Deque only"],
    answerIndex: 0,
  },
  {
    id: "tech_dsa_004",
    tag: "technical",
    prompt: "In a max-heap, the largest element is at:",
    options: ["Any leaf", "The root", "The last node", "Middle level"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_005",
    tag: "technical",
    prompt: "Worst-case time complexity of quicksort is:",
    options: ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"],
    answerIndex: 2,
  },
  {
    id: "tech_dsa_006",
    tag: "technical",
    prompt: "Which sorting algorithm is stable by default?",
    options: ["Quick sort", "Heap sort", "Merge sort", "Selection sort"],
    answerIndex: 2,
  },
  {
    id: "tech_dsa_007",
    tag: "technical",
    prompt: "A hash collision occurs when:",
    options: [
      "Two different keys map to the same hash index",
      "A key maps to an empty bucket",
      "Hash function returns negative values",
      "Table is empty",
    ],
    answerIndex: 0,
  },
  {
    id: "tech_dsa_008",
    tag: "technical",
    prompt: "Which traversal of BST gives sorted order of elements?",
    options: ["Preorder", "Inorder", "Postorder", "Level order"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_009",
    tag: "technical",
    prompt: "Time complexity of inserting into a balanced BST is:",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_010",
    tag: "technical",
    prompt: "Which graph algorithm finds shortest paths from a single source (non-negative weights)?",
    options: ["Prim", "Kruskal", "Dijkstra", "Floyd-Warshall"],
    answerIndex: 2,
  },
  {
    id: "tech_dsa_011",
    tag: "technical",
    prompt: "Floyd-Warshall algorithm computes:",
    options: ["MST", "All-pairs shortest paths", "Topological order", "Strongly connected components"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_012",
    tag: "technical",
    prompt: "Topological sorting is possible only in:",
    options: ["Undirected graphs", "DAG", "Complete graphs", "Graphs with cycles"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_013",
    tag: "technical",
    prompt: "Which data structure supports LIFO?",
    options: ["Queue", "Stack", "ArrayList", "Binary tree"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_014",
    tag: "technical",
    prompt: "In Big-O notation, dropping constants means:",
    options: ["O(2n) equals O(n)", "O(n) equals O(n^2)", "O(log n) equals O(n)", "O(1) equals O(n)"],
    answerIndex: 0,
  },
  {
    id: "tech_dsa_015",
    tag: "technical",
    prompt: "Which algorithm is used to find MST?",
    options: ["Dijkstra", "Bellman-Ford", "Kruskal", "Floyd-Warshall"],
    answerIndex: 2,
  },
  {
    id: "tech_dsa_016",
    tag: "technical",
    prompt: "A queue implemented using an array with front/rear requires what to avoid wasted space?",
    options: ["Recursion", "Circular queue", "Binary search", "Hashing"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_017",
    tag: "technical",
    prompt: "Which data structure is best suited for prefix searches (like autocomplete)?",
    options: ["Heap", "Trie", "Stack", "Graph"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_018",
    tag: "technical",
    prompt: "In a linked list, insertion at head is:",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 0,
  },
  {
    id: "tech_dsa_019",
    tag: "technical",
    prompt: "Which algorithm is used for cycle detection in directed graphs using colors/recursion stack?",
    options: ["Binary search", "DFS", "Counting sort", "Heapify"],
    answerIndex: 1,
  },
  {
    id: "tech_dsa_020",
    tag: "technical",
    prompt: "Which algorithm uses divide-and-conquer?",
    options: ["Merge sort", "Insertion sort", "Bubble sort", "Linear search"],
    answerIndex: 0,
  },

  {
    id: "tech_java_001",
    tag: "technical",
    prompt: "JVM stands for:",
    options: ["Java Visual Model", "Java Virtual Machine", "Java Variable Manager", "Just Virtual Memory"],
    answerIndex: 1,
  },
  {
    id: "tech_java_002",
    tag: "technical",
    prompt: "JDK contains:",
    options: ["Only JVM", "Only JRE", "JRE + development tools", "Only compiler"],
    answerIndex: 2,
  },
  {
    id: "tech_java_003",
    tag: "technical",
    prompt: "Which keyword prevents a method from being overridden?",
    options: ["static", "final", "abstract", "volatile"],
    answerIndex: 1,
  },
  {
    id: "tech_java_004",
    tag: "technical",
    prompt: "Which collection does NOT allow duplicates?",
    options: ["List", "Set", "ArrayList", "LinkedList"],
    answerIndex: 1,
  },
  {
    id: "tech_java_005",
    tag: "technical",
    prompt: "Which is true about an interface in Java?",
    options: [
      "It can have instance fields with state",
      "A class can implement multiple interfaces",
      "Interfaces cannot have methods",
      "Interfaces cannot be used for polymorphism",
    ],
    answerIndex: 1,
  },
  {
    id: "tech_java_006",
    tag: "technical",
    prompt: "Which exception is unchecked?",
    options: ["IOException", "SQLException", "NullPointerException", "ClassNotFoundException"],
    answerIndex: 2,
  },
  {
    id: "tech_java_007",
    tag: "technical",
    prompt: "Which keyword is used to inherit a class?",
    options: ["this", "super", "extends", "implements"],
    answerIndex: 2,
  },
  {
    id: "tech_java_008",
    tag: "technical",
    prompt: "Overloading means:",
    options: [
      "Same method name with different parameter list",
      "Same method name with same parameters but different return type",
      "Same class name used twice",
      "Changing variable values at runtime",
    ],
    answerIndex: 0,
  },
  {
    id: "tech_java_009",
    tag: "technical",
    prompt: "Which is a valid way to create a thread in Java?",
    options: [
      "Implement Runnable or extend Thread",
      "Only extend Object",
      "Only use reflection",
      "Only use enum",
    ],
    answerIndex: 0,
  },
  {
    id: "tech_java_010",
    tag: "technical",
    prompt: "Which modifier makes a variable visible only within the same class?",
    options: ["public", "protected", "private", "default (package-private)"],
    answerIndex: 2,
  },

  {
    id: "tech_misc_001",
    tag: "technical",
    prompt: "REST typically uses which protocol?",
    options: ["HTTP", "FTP", "SMTP", "SNMP"],
    answerIndex: 0,
  },
  {
    id: "tech_misc_002",
    tag: "technical",
    prompt: "HTTP method generally used to update an existing resource is:",
    options: ["GET", "POST", "PUT", "TRACE"],
    answerIndex: 2,
  },
  {
    id: "tech_misc_003",
    tag: "technical",
    prompt: "Which HTTP status code means 'Not Found'?",
    options: ["200", "301", "404", "500"],
    answerIndex: 2,
  },
  {
    id: "tech_misc_004",
    tag: "technical",
    prompt: "Which data structure is best for O(1) average lookups by key?",
    options: ["Array", "Hash table", "Binary search tree", "Linked list"],
    answerIndex: 1,
  },
  {
    id: "tech_misc_005",
    tag: "technical",
    prompt: "In SQL, which constraint ensures unique values in a column (can allow NULLs depending on DB)?",
    options: ["CHECK", "UNIQUE", "FOREIGN KEY", "DEFAULT"],
    answerIndex: 1,
  },
  {
    id: "tech_misc_006",
    tag: "technical",
    prompt: "Which is an example of symmetric encryption?",
    options: ["AES", "RSA", "DSA", "ECC"],
    answerIndex: 0,
  },
  {
    id: "tech_misc_007",
    tag: "technical",
    prompt: "Which layer in TCP/IP model corresponds to OSI Transport layer?",
    options: ["Application", "Transport", "Internet", "Link"],
    answerIndex: 1,
  },
  {
    id: "tech_misc_008",
    tag: "technical",
    prompt: "A race condition occurs when:",
    options: [
      "Two threads access shared data without proper synchronization",
      "CPU is faster than memory",
      "Disk is slow",
      "A program compiles twice",
    ],
    answerIndex: 0,
  },
  {
    id: "tech_misc_009",
    tag: "technical",
    prompt: "Which of these is a NoSQL database type?",
    options: ["Relational", "Document store", "Normalization", "BCNF"],
    answerIndex: 1,
  },
  {
    id: "tech_misc_010",
    tag: "technical",
    prompt: "CAP theorem says a distributed system can provide at most two of:",
    options: [
      "Consistency, Availability, Partition tolerance",
      "Concurrency, Accuracy, Performance",
      "Caching, Availability, Persistence",
      "Correctness, Atomicity, Privacy",
    ],
    answerIndex: 0,
  },

  // --------------------
  // QUANT (10)
  // --------------------
  {
    id: "quant_001",
    tag: "quant",
    prompt: "If 6 pens cost ₹90, what is the cost of 10 pens?",
    options: ["₹120", "₹130", "₹140", "₹150"],
    answerIndex: 0,
  },
  {
    id: "quant_002",
    tag: "quant",
    prompt: "A train covers 180 km in 3 hours. Speed = ?",
    options: ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
    answerIndex: 2,
  },
  {
    id: "quant_003",
    tag: "quant",
    prompt: "20% of 250 is:",
    options: ["25", "40", "50", "60"],
    answerIndex: 2,
  },
  {
    id: "quant_004",
    tag: "quant",
    prompt: "If A:B = 2:3 and B:C = 4:5, then A:C = ?",
    options: ["8:15", "2:5", "4:9", "6:10"],
    answerIndex: 0,
  },
  {
    id: "quant_005",
    tag: "quant",
    prompt: "Simple interest on ₹1000 at 10% per annum for 2 years is:",
    options: ["₹100", "₹150", "₹200", "₹250"],
    answerIndex: 2,
  },
  {
    id: "quant_006",
    tag: "quant",
    prompt: "LCM of 6 and 8 is:",
    options: ["12", "18", "24", "48"],
    answerIndex: 2,
  },
  {
    id: "quant_007",
    tag: "quant",
    prompt: "If x + 5 = 17, x = ?",
    options: ["10", "11", "12", "13"],
    answerIndex: 2,
  },
  {
    id: "quant_008",
    tag: "quant",
    prompt: "A shop gives 10% discount on ₹500. Selling price = ?",
    options: ["₹450", "₹460", "₹470", "₹480"],
    answerIndex: 0,
  },
  {
    id: "quant_009",
    tag: "quant",
    prompt: "If 5 workers finish a job in 12 days, how many days for 10 workers (same rate)?",
    options: ["3", "5", "6", "8"],
    answerIndex: 2,
  },
  {
    id: "quant_010",
    tag: "quant",
    prompt: "Which is larger?",
    options: ["0.8", "0.08", "0.808", "0.88"],
    answerIndex: 3,
  },

  // --------------------
  // REASONING (10)
  // --------------------
  {
    id: "reason_001",
    tag: "reasoning",
    prompt: "Find the odd one out: 2, 3, 5, 9, 11",
    options: ["2", "3", "5", "9"],
    answerIndex: 3,
  },
  {
    id: "reason_002",
    tag: "reasoning",
    prompt: "If SOUTH is coded as T P V U I, then NORTH is coded as:",
    options: ["O P S U I", "O Q S U I", "O P R U I", "O P S V I"],
    answerIndex: 0,
  },
  {
    id: "reason_003",
    tag: "reasoning",
    prompt: "Complete the series: A, C, F, J, O, ?",
    options: ["T", "U", "V", "W"],
    answerIndex: 1,
  },
  {
    id: "reason_004",
    tag: "reasoning",
    prompt: "In a certain code, CAT = 24. Then DOG = ? (A=1, B=2...)",
    options: ["26", "28", "30", "32"],
    answerIndex: 0,
  },
  {
    id: "reason_005",
    tag: "reasoning",
    prompt: "Find the next number: 1, 4, 9, 16, ?",
    options: ["20", "24", "25", "36"],
    answerIndex: 2,
  },
  {
    id: "reason_006",
    tag: "reasoning",
    prompt: "If all Bloops are Razzies and all Razzies are Lazzies, then all Bloops are:",
    options: ["Lazzies", "Not Lazzies", "Some Lazzies", "Cannot be determined"],
    answerIndex: 0,
  },
  {
    id: "reason_007",
    tag: "reasoning",
    prompt: "Find the missing term: 5, 11, 23, 47, ?",
    options: ["93", "94", "95", "96"],
    answerIndex: 2,
  },
  {
    id: "reason_008",
    tag: "reasoning",
    prompt: "If 2 + 3 = 13 and 3 + 4 = 25, then 4 + 5 = ? (pattern: a^2 + b^2)",
    options: ["41", "39", "37", "43"],
    answerIndex: 0,
  },
  {
    id: "reason_009",
    tag: "reasoning",
    prompt: "Choose the correct mirror image of 'E'.",
    options: ["Ǝ", "E", "∃", "Σ"],
    answerIndex: 0,
  },
  {
    id: "reason_010",
    tag: "reasoning",
    prompt: "If today is Monday, what day will it be after 45 days?",
    options: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    answerIndex: 3,
  },

  // --------------------
  // ENGLISH (10)
  // --------------------
  {
    id: "eng_001",
    tag: "english",
    prompt: "Choose the correct spelling:",
    options: ["Accomodate", "Acommodate", "Accommodate", "Acomodate"],
    answerIndex: 2,
  },
  {
    id: "eng_002",
    tag: "english",
    prompt: "Synonym of 'rapid' is:",
    options: ["Slow", "Quick", "Late", "Weak"],
    answerIndex: 1,
  },
  {
    id: "eng_003",
    tag: "english",
    prompt: "Antonym of 'increase' is:",
    options: ["Expand", "Enhance", "Decrease", "Add"],
    answerIndex: 2,
  },
  {
    id: "eng_004",
    tag: "english",
    prompt: "Choose the correct sentence:",
    options: [
      "He don't like coffee.",
      "He doesn't like coffee.",
      "He doesn't likes coffee.",
      "He not likes coffee.",
    ],
    answerIndex: 1,
  },
  {
    id: "eng_005",
    tag: "english",
    prompt: "Fill in the blank: She ___ to office every day.",
    options: ["go", "goes", "gone", "going"],
    answerIndex: 1,
  },
  {
    id: "eng_006",
    tag: "english",
    prompt: "Choose the correct passive voice: 'They completed the work.'",
    options: [
      "The work has completed by them.",
      "The work was completed by them.",
      "The work is completed by them.",
      "The work had complete by them.",
    ],
    answerIndex: 1,
  },
  {
    id: "eng_007",
    tag: "english",
    prompt: "One word for 'able to use both hands equally well':",
    options: ["Ambidextrous", "Ambiguous", "Amicable", "Amorphous"],
    answerIndex: 0,
  },
  {
    id: "eng_008",
    tag: "english",
    prompt: "Choose the correct article: He is ___ honest man.",
    options: ["a", "an", "the", "no article"],
    answerIndex: 1,
  },
  {
    id: "eng_009",
    tag: "english",
    prompt: "Meaning of 'brevity' is:",
    options: ["Length", "Shortness", "Anger", "Clarity"],
    answerIndex: 1,
  },
  {
    id: "eng_010",
    tag: "english",
    prompt: "Choose the correct preposition: He is good ___ math.",
    options: ["in", "on", "at", "by"],
    answerIndex: 2,
  },

  // --------------------
  // GK (10)
  // --------------------
  {
    id: "gk_001",
    tag: "gk",
    prompt: "The Constitution of India came into effect on:",
    options: ["15 Aug 1947", "26 Jan 1950", "2 Oct 1949", "26 Nov 1949"],
    answerIndex: 1,
  },
  {
    id: "gk_002",
    tag: "gk",
    prompt: "The currency of Japan is:",
    options: ["Yen", "Won", "Dollar", "Peso"],
    answerIndex: 0,
  },
  {
    id: "gk_003",
    tag: "gk",
    prompt: "Which planet is known as the Red Planet?",
    options: ["Earth", "Mars", "Jupiter", "Venus"],
    answerIndex: 1,
  },
  {
    id: "gk_004",
    tag: "gk",
    prompt: "The national animal of India is:",
    options: ["Lion", "Tiger", "Elephant", "Leopard"],
    answerIndex: 1,
  },
  {
    id: "gk_005",
    tag: "gk",
    prompt: "The largest ocean is:",
    options: ["Indian", "Arctic", "Atlantic", "Pacific"],
    answerIndex: 3,
  },
  {
    id: "gk_006",
    tag: "gk",
    prompt: "Which gas is most abundant in Earth's atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
    answerIndex: 1,
  },
  {
    id: "gk_007",
    tag: "gk",
    prompt: "The SI unit of electric current is:",
    options: ["Volt", "Watt", "Ampere", "Ohm"],
    answerIndex: 2,
  },
  {
    id: "gk_008",
    tag: "gk",
    prompt: "Which is the largest continent by area?",
    options: ["Africa", "Asia", "Europe", "Antarctica"],
    answerIndex: 1,
  },
  {
    id: "gk_009",
    tag: "gk",
    prompt: "The headquarters of the United Nations is in:",
    options: ["Geneva", "New York", "Paris", "London"],
    answerIndex: 1,
  },
  {
    id: "gk_010",
    tag: "gk",
    prompt: "Which instrument is used to measure atmospheric pressure?",
    options: ["Thermometer", "Barometer", "Hygrometer", "Anemometer"],
    answerIndex: 1,
  },

  // --------------------
  // IFFCO (10) — from official sources (annual report + production units page)
  // --------------------
  {
    id: "iffco_001",
    tag: "iffco",
    prompt: "IFFCO stands for:",
    options: [
      "Indian Farmers Finance Cooperative Ltd.",
      "Indian Farmers Fertiliser Cooperative Limited",
      "Indian Federation of Fertiliser Companies",
      "Indian Fertiliser Funding Corporation",
    ],
    answerIndex: 1,
  },
  {
    id: "iffco_002",
    tag: "iffco",
    prompt: "IFFCO (Indian Farmers Fertiliser Cooperative Ltd.) was established on:",
    options: ["3 Nov 1967", "15 Aug 1947", "26 Jan 1950", "1 Apr 1974"],
    answerIndex: 0,
  },
  {
    id: "iffco_003",
    tag: "iffco",
    prompt: "IFFCO Head Office is in:",
    options: ["Mumbai", "New Delhi", "Kolkata", "Chennai"],
    answerIndex: 1,
  },
  {
    id: "iffco_004",
    tag: "iffco",
    prompt: "IFFCO is primarily a:",
    options: ["Private company", "Multi-State Cooperative Society", "State government department", "Foreign MNC subsidiary"],
    answerIndex: 1,
  },
  {
    id: "iffco_005",
    tag: "iffco",
    prompt: "How many major IFFCO production units are listed on the official site?",
    options: ["3", "4", "5", "6"],
    answerIndex: 2,
  },
  {
    id: "iffco_006",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Kalol", "Pune", "Jaipur", "Bhopal"],
    answerIndex: 0,
  },
  {
    id: "iffco_007",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Aonla", "Surat", "Indore", "Noida"],
    answerIndex: 0,
  },
  {
    id: "iffco_008",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Paradeep", "Ranchi", "Guwahati", "Agra"],
    answerIndex: 0,
  },
  {
    id: "iffco_009",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Kandla", "Varanasi", "Nagpur", "Chandigarh"],
    answerIndex: 0,
  },
  {
    id: "iffco_010",
    tag: "iffco",
    prompt: "Which of these is an IFFCO production unit location?",
    options: ["Phulpur", "Lucknow", "Hyderabad", "Patna"],
    answerIndex: 0,
  },
  // --------------------
  // IFFCO CBT 1 REAL RECALL QUESTIONS (CS TECHNICAL)
  // --------------------
  {
    id: "cbt1_001",
    tag: "technical",
    prompt: "Changing one employee department requires updates in many records. Which anomaly is present?",
    options: ["Phantom Read", "Update Anomaly", "Lost Update", "Dirty Read"],
    answerIndex: 1,
  },
  {
    id: "cbt1_002",
    tag: "technical",
    prompt: "Login requires password plus approval on a registered mobile device. Which mechanism is used?",
    options: ["Multi-Factor Authentication", "CAPTCHA Verification", "Password Hashing", "Single Sign-On"],
    answerIndex: 0,
  },
  {
    id: "cbt1_003",
    tag: "technical",
    prompt: "A site works by IP address but not by domain name. Which service should be checked first?",
    options: ["FTP", "DHCP", "SMTP", "DNS"],
    answerIndex: 3,
  },
  {
    id: "cbt1_004",
    tag: "technical",
    prompt: "A transaction updates two databases; if one fails, both must roll back. Which protocol fits?",
    options: ["Two-Phase Commit (2PC)", "Raft Consensus", "Lamport Clock", "Gossip Protocol"],
    answerIndex: 0,
  },
  {
    id: "cbt1_005",
    tag: "technical",
    prompt: "A loop recomputes an expression whose operands do not change. Which optimization removes this repetition?",
    options: ["Loop Unrolling", "Register Spilling", "Dead Code Elimination", "Common Subexpression Elimination"],
    answerIndex: 3,
  },
  {
    id: "cbt1_006",
    tag: "technical",
    prompt: "Free memory is scattered into small non-contiguous blocks despite enough total memory. What is this?",
    options: ["Thrashing", "Deadlock", "External Fragmentation", "Internal Fragmentation"],
    answerIndex: 2,
  },
  {
    id: "cbt1_007",
    tag: "technical",
    prompt: "A BST becomes nearly sorted and search time approaches O(n). Which change best restores efficient search?",
    options: ["Use a self-balancing tree such as AVL", "Increase application RAM", "Store duplicate keys in lists", "Convert the tree into a queue"],
    answerIndex: 0,
  },
  {
    id: "cbt1_008",
    tag: "technical",
    prompt: "RAM is insufficient, yet applications continue by moving inactive pages to storage. Which mechanism enables this?",
    options: ["Memory Fragmentation", "Virtual Memory", "Direct Memory Access", "Register Allocation"],
    answerIndex: 1,
  },
  {
    id: "cbt1_009",
    tag: "technical",
    prompt: "Which SQL clause filters grouped results after aggregation?",
    options: ["ORDER BY", "HAVING", "WHERE", "DISTINCT"],
    answerIndex: 1,
  },
  {
    id: "cbt1_010",
    tag: "technical",
    prompt: "An administrator must block unauthorized inbound connections while allowing approved traffic. Which control fits best?",
    options: ["Repeater", "Firewall", "Layer-2 Switch", "Network Hub"],
    answerIndex: 1,
  },
  {
    id: "cbt1_011",
    tag: "technical",
    prompt: "A compiler must target multiple processors with minimal front-end changes. Which design supports this?",
    options: ["Independent syntax analyzers", "Separate lexical analyzers", "Architecture-specific symbol tables", "Retargetable compiler using common IR"],
    answerIndex: 3,
  },
  {
    id: "cbt1_012",
    tag: "technical",
    prompt: "A dynamic array doubles capacity when full. What is the amortized insertion complexity?",
    options: ["O(log n)", "O(1)", "O(n)", "O(n log n)"],
    answerIndex: 1,
  },
  {
    id: "cbt1_013",
    tag: "technical",
    prompt: "A weighted road graph has non-negative edge weights. Which algorithm gives single-source shortest paths?",
    options: ["Depth-First Search", "Breadth-First Search", "Dijkstra's Algorithm", "Prim's Algorithm"],
    answerIndex: 2,
  },
  {
    id: "cbt1_014",
    tag: "technical",
    prompt: "A processor executes independent later instructions before earlier ones finish while preserving correctness. Technique?",
    options: ["Instruction Fusion", "Loop Unrolling", "Static Scheduling", "Out-of-Order Execution"],
    answerIndex: 3,
  },
  {
    id: "cbt1_015",
    tag: "technical",
    prompt: "A database allows blank middle names but must prevent duplicate university email addresses. Which constraint fits?",
    options: ["CHECK", "UNIQUE", "NOT NULL", "DEFAULT"],
    answerIndex: 1,
  },
  {
    id: "cbt1_016",
    tag: "technical",
    prompt: "Design changes are evaluated for maintainability, scalability, reliability, security and performance. Which activity is this?",
    options: ["Architectural Design Review", "Database Backup", "Code Formatting", "Unit Testing"],
    answerIndex: 0,
  },
  {
    id: "cbt1_017",
    tag: "technical",
    prompt: "A transaction updates inventory but fails before sales entry. Recovery restores the earlier state. Which ACID property applies?",
    options: ["Durability", "Consistency", "Isolation", "Atomicity"],
    answerIndex: 3,
  },
  {
    id: "cbt1_018",
    tag: "technical",
    prompt: "Variable-size allocations fail due to scattered free memory despite enough total space. What helps?",
    options: ["Memory Mapping", "Demand Paging", "Memory Compaction", "Copy-on-Write"],
    answerIndex: 2,
  },
  {
    id: "cbt1_019",
    tag: "technical",
    prompt: "A problem has overlapping subproblems and needs an optimal solution. Which technique fits best?",
    options: ["Dynamic Programming", "Greedy Algorithm", "Divide and Conquer", "Backtracking"],
    answerIndex: 0,
  },
  {
    id: "cbt1_020",
    tag: "technical",
    prompt: "A workstation automatically receives IP address, subnet mask, gateway and DNS server. Which service assigns these?",
    options: ["DHCP", "NAT", "ARP", "DNS"],
    answerIndex: 0,
  },
  {
    id: "cbt1_021",
    tag: "technical",
    prompt: "Which scheduling method allocates CPU time slices to processes?",
    options: ["Segmentation", "Paging", "Round Robin", "FIFO Scheduling"],
    answerIndex: 2,
  },
  {
    id: "cbt1_022",
    tag: "technical",
    prompt: "Which OS mechanism prevents one application from accessing another application's memory?",
    options: ["Memory Protection", "Caching", "Multithreading", "Spooling"],
    answerIndex: 0,
  },
  {
    id: "cbt1_023",
    tag: "technical",
    prompt: "A server uses lightweight units sharing one address space instead of one process per request. Main benefit?",
    options: [
      "Lower context-switch overhead and better scalability",
      "No synchronization required",
      "Complete memory isolation",
      "Automatic race-condition elimination",
    ],
    answerIndex: 0,
  },
  {
    id: "cbt1_024",
    tag: "technical",
    prompt: "What is a key advantage of partitioning a large industrial database table?",
    options: [
      "Removes indexes",
      "Eliminates backups",
      "Reduces user count",
      "Improves manageability and query performance",
    ],
    answerIndex: 3,
  },
  {
    id: "cbt1_025",
    tag: "technical",
    prompt: "A device must search thousands of malware signatures in a data stream. Which algorithm fits best?",
    options: ["Binary Search", "Quick Sort", "Aho-Corasick", "Boyer-Moore"],
    answerIndex: 2,
  },
  {
    id: "cbt1_026",
    tag: "technical",
    prompt: "An unweighted graph needs the minimum number of edges between two vertices. Which algorithm fits?",
    options: ["Bellman-Ford Algorithm", "Breadth-First Search", "Depth-First Search", "Prim's Algorithm"],
    answerIndex: 1,
  },
  {
    id: "cbt1_027",
    tag: "technical",
    prompt: "Which algorithm constructs a minimum-cost spanning tree in a connected weighted graph?",
    options: ["Bellman-Ford Algorithm", "Dijkstra's Algorithm", "Kruskal's Algorithm", "Topological Sort"],
    answerIndex: 2,
  },
  {
    id: "cbt1_028",
    tag: "technical",
    prompt: "Independent tasks have almost no communication. Which property enables near-linear speedup?",
    options: [
      "Sequential Dependencies",
      "Shared Critical Sections",
      "Frequent Lock Contention",
      "High Task Parallelism",
    ],
    answerIndex: 3,
  },
  {
    id: "cbt1_029",
    tag: "technical",
    prompt: "A compiler replaces multiplication by a power of two with a shift. Which optimization is this?",
    options: [
      "Strength Reduction",
      "Loop Interchange",
      "Tail Recursion Elimination",
      "Peephole Optimization",
    ],
    answerIndex: 0,
  },
  {
    id: "cbt1_030",
    tag: "technical",
    prompt: "A language needs matching brackets with arbitrary nesting. Simplest grammar class?",
    options: [
      "Regular Grammar",
      "Unrestricted Grammar",
      "Context-Free Grammar",
      "Context-Sensitive Grammar",
    ],
    answerIndex: 2,
  },
  {
    id: "cbt1_031",
    tag: "technical",
    prompt: "A program waits mostly for main-memory data rather than computing. Which enhancement helps most?",
    options: [
      "Deeper Pipeline",
      "Higher Clock Frequency",
      "Additional ALUs",
      "Larger Last-Level Cache",
    ],
    answerIndex: 3,
  },
  {
    id: "cbt1_032",
    tag: "technical",
    prompt: "A banking table must uniquely identify each account and be referenced by transaction tables. What should be used?",
    options: ["Primary Key on Account ID", "Check constraint on Balance", "Unique Customer Name", "Index on Balance"],
    answerIndex: 0,
  },
  {
    id: "cbt1_033",
    tag: "technical",
    prompt: "Equality searches on a 40-million-row product-code column are slow; inserts are infrequent. What helps most?",
    options: ["Increase VARCHAR length", "Normalize into more tables", "Store Product Code as BLOB", "Create an index on Product Code"],
    answerIndex: 3,
  },
  {
    id: "cbt1_034",
    tag: "technical",
    prompt: "A database must remain available during partitions, accepting temporarily stale replica reads. Which model fits?",
    options: ["Sequential Consistency", "Linearizability", "Eventual Consistency", "Strict Serializability"],
    answerIndex: 2,
  },
  {
    id: "cbt1_035",
    tag: "technical",
    prompt: "Many threads contend for a shared structure in read-heavy workload. Which lock improves scalability?",
    options: ["Counting Semaphore", "Binary Semaphore", "Barrier Synchronization", "Read-Write Lock"],
    answerIndex: 3,
  },
  {
    id: "cbt1_036",
    tag: "technical",
    prompt: "A low-priority thread holds a resource needed by a high-priority thread. What prevents priority inversion?",
    options: ["Round Robin Scheduling", "Priority Inheritance", "Multilevel Feedback Queue", "Time Slicing"],
    answerIndex: 1,
  },
  {
    id: "cbt1_037",
    tag: "technical",
    prompt: "Which resource is shared among threads belonging to the same process?",
    options: ["Program counter", "Virtual address space", "Stack", "Register set"],
    answerIndex: 1,
  },
  {
    id: "cbt1_038",
    tag: "technical",
    prompt: "Two processes waiting on each other cause what issue?",
    options: ["Fragmentation", "Paging", "Thrashing", "Deadlock"],
    answerIndex: 3,
  },
  {
    id: "cbt1_039",
    tag: "technical",
    prompt: "Which operating system subsystem is primarily responsible for organizing files, directories and metadata on storage devices?",
    options: ["Virtual Memory Manager", "File System", "Process Scheduler", "I/O Scheduler"],
    answerIndex: 1,
  },
  {
    id: "cbt1_040",
    tag: "technical",
    prompt: "Lightweight environments share the host kernel while isolating processes and file systems. Key OS feature?",
    options: ["Process Forking", "Demand Paging", "Namespaces", "Memory-Mapped Files"],
    answerIndex: 2,
  },
  {
    id: "cbt1_041",
    tag: "technical",
    prompt: "A parallel graph algorithm slows due to frequent boundary-data exchange. What limits scalability?",
    options: ["Communication Overhead", "Branch Prediction", "Cache Coherence", "Instruction Pipelining"],
    answerIndex: 0,
  },
  {
    id: "cbt1_042",
    tag: "technical",
    prompt: "An in-memory index is searched very frequently but updated only occasionally. It requires sorted records and worst-case O(log n) search, insert and delete. Which structure provides the fastest guaranteed lookup while still maintaining balance?",
    options: ["Splay Tree", "AVL Tree", "Red-Black Tree", "B+ Tree"],
    answerIndex: 1,
  },
  {
    id: "cbt1_043",
    tag: "technical",
    prompt: "An NP-hard optimization problem must be solved for very large instances. A polynomial-time algorithm returns a solution guaranteed to be within a known factor of the optimal. Which class of algorithms is described?",
    options: ["Heuristic Search", "Randomized Algorithm", "Exact Algorithm", "Approximation Algorithm"],
    answerIndex: 3,
  },
  {
    id: "cbt1_044",
    tag: "technical",
    prompt: "A scheduler repeatedly executes the highest-priority process and inserts new tasks efficiently. Best structure?",
    options: ["Binary Heap", "Fibonacci Heap", "Balanced BST", "Binomial Heap"],
    answerIndex: 0,
  },
  {
    id: "cbt1_045",
    tag: "technical",
    prompt: "A data structure must support efficient insertion and deletion at both the front and rear while providing these operations as part of its interface. Which abstract data type is most appropriate?",
    options: ["Deque", "Stack", "Priority Queue", "Queue"],
    answerIndex: 0,
  },
  {
    id: "cbt1_046",
    tag: "technical",
    prompt: "A graph has negative edge weights but no negative cycles. Which single-source shortest path algorithm works?",
    options: ["Bellman-Ford Algorithm", "Prim's Algorithm", "A* Search", "Dijkstra's Algorithm"],
    answerIndex: 0,
  },
  {
    id: "cbt1_047",
    tag: "technical",
    prompt: "A maintenance application frequently inserts and deletes records from the middle of a collection. Which data structure is most suitable?",
    options: ["Linked List", "Heap", "Array", "Stack"],
    answerIndex: 0,
  },
  {
    id: "cbt1_048",
    tag: "technical",
    prompt: "A grammar gives multiple parse trees for the same expression. What correction is needed?",
    options: ["Expand symbol table", "Introduce constant propagation", "Eliminate grammar ambiguity", "Increase lexical lookahead"],
    answerIndex: 2,
  },
  {
    id: "cbt1_049",
    tag: "technical",
    prompt: "A parser must detect syntax errors early while scanning left to right without heavy backtracking. Desired property?",
    options: ["Nondeterministic Recognition", "Left Recursion", "Ambiguous Grammar", "Deterministic Parsing"],
    answerIndex: 3,
  },
  {
    id: "cbt1_050",
    tag: "technical",
    prompt: "Incorrect conditional-branch outcomes often reduce processor performance. Which feature addresses this?",
    options: ["Memory Interleaving", "Dynamic Branch Prediction", "Cache Prefetching", "SIMD Execution"],
    answerIndex: 1,
  },
  {
    id: "cbt1_051",
    tag: "technical",
    prompt: "Which SDLC model is best when requirements are well-defined and stable?",
    options: ["Agile", "Spiral", "DevOps", "Waterfall"],
    answerIndex: 3,
  },
  {
    id: "cbt1_052",
    tag: "technical",
    prompt: "A search engine processes billions of documents and needs to retrieve the most relevant ones within milliseconds. Which algorithmic approach is most fundamental for efficient text retrieval?",
    options: ["A* Search", "Bellman-Ford Algorithm", "TF-IDF with Inverted Index", "PageRank"],
    answerIndex: 2,
  },
  {
    id: "cbt1_053",
    tag: "technical",
    prompt: "A directed dependency graph must be checked for cycles before scheduling. Which traversal fits?",
    options: ["Depth-First Search", "Kruskal's Algorithm", "Dijkstra's Algorithm", "Breadth-First Search"],
    answerIndex: 0,
  },
  {
    id: "cbt1_054",
    tag: "technical",
    prompt: "A file system delays writes but must recover reliably after crashes. Which mechanism supports this?",
    options: ["Deadlock Detection", "Segmentation", "Journaling", "Swapping"],
    answerIndex: 2,
  },
  {
    id: "cbt1_055",
    tag: "technical",
    prompt: "A parallel program spends more time synchronizing than computing. What improves performance?",
    options: ["Reduce Synchronization Frequency", "Increase Thread Count", "Deepen Instruction Pipeline", "Increase Cache Size"],
    answerIndex: 0,
  },
  {
    id: "cbt1_056",
    tag: "technical",
    prompt: "An instruction needs the result of the immediately preceding instruction. Which hardware minimizes the stall?",
    options: ["Data Forwarding (Bypassing)", "Branch Prediction", "Register Renaming", "Out-of-Order Execution"],
    answerIndex: 0,
  },
  {
    id: "cbt1_057",
    tag: "technical",
    prompt: "A disk-resident index must minimize disk I/O for millions of records. Which structure is best?",
    options: ["Red-Black Tree", "AVL Tree", "B+ Tree", "Trie"],
    answerIndex: 2,
  },
  {
    id: "cbt1_058",
    tag: "technical",
    prompt: "Module dependencies form a DAG. Which algorithm gives a valid compilation order?",
    options: ["Breadth-First Search", "Kruskal's Algorithm", "Floyd-Warshall Algorithm", "Topological Sort"],
    answerIndex: 3,
  },
  {
    id: "cbt1_059",
    tag: "technical",
    prompt: "Production, Finance and Research networks must communicate with separate IP schemes. Which device routes traffic?",
    options: ["Ethernet Hub", "Layer-2 Switch", "Wireless Access Point", "Router"],
    answerIndex: 3,
  },
  {
    id: "cbt1_060",
    tag: "technical",
    prompt: "Millions of sorted shipment records are searched often and updated nightly. Which search strategy is best?",
    options: ["Depth-First Search", "Linear Search", "Breadth-First Search", "Binary Search"],
    answerIndex: 3,
  },
  {
    id: "cbt1_061",
    tag: "technical",
    prompt: "Which dataset characteristic is most likely to reduce the predictive accuracy of a supervised machine learning model?",
    options: ["Feature normalization", "Larger training dataset", "Missing and inconsistent values", "Balanced class distribution"],
    answerIndex: 2,
  },
  {
    id: "cbt1_062",
    tag: "technical",
    prompt: "An LRU cache needs O(1) lookup and O(1) least-recent eviction. Which implementation fits?",
    options: ["B+ Tree + Dynamic Array", "AVL Tree + Queue", "Skip List + Circular Buffer", "Hash Table + Doubly Linked List"],
    answerIndex: 3,
  },
  {
    id: "cbt1_063",
    tag: "technical",
    prompt: "A compiler checks arbitrarily nested parentheses. Which model is most appropriate?",
    options: ["Finite Automaton", "Turing Machine", "Pushdown Automaton", "Linear Bounded Automaton"],
    answerIndex: 2,
  },
  {
    id: "cbt1_064",
    tag: "technical",
    prompt: "A server waits on disk I/O for many client requests. Which model improves CPU utilization?",
    options: ["Cooperative Scheduling", "Static Partitioning", "Non-Preemptive Scheduling", "Asynchronous I/O"],
    answerIndex: 3,
  },
  {
    id: "cbt1_065",
    tag: "technical",
    prompt: "A sort must guarantee O(n log n) worst-case performance and support external sorting. Which is preferred?",
    options: ["Merge Sort", "Quick Sort", "Heap Sort", "Shell Sort"],
    answerIndex: 0,
  },
  {
    id: "cbt1_066",
    tag: "technical",
    prompt: "The same arithmetic operation runs on thousands of independent data elements. Which feature helps most?",
    options: ["Simultaneous Multithreading", "Superscalar Dispatch", "SIMD Execution", "Out-of-Order Execution"],
    answerIndex: 2,
  },
  {
    id: "cbt1_067",
    tag: "technical",
    prompt: "A system elects a new leader after coordinator failure and replicates logs. Which algorithm fits?",
    options: ["Chandy-Lamport", "Vector Clocks", "Raft", "Two-Phase Commit"],
    answerIndex: 2,
  },
  {
    id: "cbt1_068",
    tag: "technical",
    prompt: "A text editor supports frequent edits near cursor in very large documents. Which structure is most suitable?",
    options: ["Doubly Linked List", "Rope", "Gap Buffer", "Piece Table"],
    answerIndex: 2,
  },
  {
    id: "cbt1_069",
    tag: "technical",
    prompt: "A compiler must identify keywords, identifiers and literals before parsing. Which phase does this?",
    options: ["Semantic Analysis", "Syntax Analysis", "Intermediate Code Generation", "Lexical Analysis"],
    answerIndex: 3,
  },
  {
    id: "cbt1_070",
    tag: "technical",
    prompt: "A data warehouse has slow analytical reports despite indexing; updates occur once daily. What helps most?",
    options: ["TEXT columns for indexed fields", "Unrelated table splits", "Controlled denormalization to reduce joins", "More foreign key constraints"],
    answerIndex: 2,
  },
  {
    id: "cbt1_071",
    tag: "technical",
    prompt: "Undo stores operations and removes them only in reverse order. Which implementation best fits?",
    options: ["Deque", "Circular Buffer", "Stack", "Doubly Linked List"],
    answerIndex: 2,
  },
  {
    id: "cbt1_072",
    tag: "technical",
    prompt: "Which traversal visits root, left subtree, then right subtree?",
    options: ["Postorder", "Level Order", "Preorder", "Inorder"],
    answerIndex: 2,
  },
  {
    id: "cbt1_073",
    tag: "technical",
    prompt: "An online exam system must keep running if one app server fails. Which design helps most?",
    options: ["Higher CPU Clock Speed", "Compressed Static Images", "Redundant Load-Balanced Servers", "Larger Database Cache"],
    answerIndex: 2,
  },
  {
    id: "cbt1_074",
    tag: "technical",
    prompt: "Repeated key lookups must improve from O(n) to average O(1), accepting extra memory. What is best?",
    options: ["Linked List", "Binary Heap", "Hash Table", "Queue"],
    answerIndex: 2,
  },
  {
    id: "cbt1_075",
    tag: "technical",
    prompt: "A networking application needs to check millions of IP addresses against a blacklist that updates hourly. False positives must be minimized but occasional false positives are acceptable. Which data structure is most appropriate?",
    options: ["Hash Table", "Bloom Filter", "Binary Search Tree", "Trie"],
    answerIndex: 1,
  },
  {
    id: "cbt1_076",
    tag: "technical",
    prompt: "What is the main purpose of a transaction log?",
    options: ["Store passwords", "Create indexes", "Enable recovery and auditing", "Manage sessions"],
    answerIndex: 2,
  },
  {
    id: "cbt1_077",
    tag: "technical",
    prompt: "Which database object automatically executes when specific events occur?",
    options: ["Trigger", "View", "Cursor", "Schema"],
    answerIndex: 0,
  },
  {
    id: "cbt1_078",
    tag: "technical",
    prompt: "What is the purpose of a semaphore?",
    options: ["Encrypt files", "Route packets", "Compress memory", "Synchronize access to shared resources"],
    answerIndex: 3,
  },
  {
    id: "cbt1_079",
    tag: "technical",
    prompt: "A protocol validates fixed-format headers with no nesting. Which model is sufficient?",
    options: ["Context-Sensitive Grammar", "Pushdown Automaton", "Turing Machine", "Deterministic Finite Automaton"],
    answerIndex: 3,
  },
  {
    id: "cbt1_080",
    tag: "technical",
    prompt: "A team is designing a web API for a resource-oriented system. They want to follow standard architectural principles where resources are represented as nouns and operations are represented by HTTP methods. Which design principle is this?",
    options: ["SOAP-based Design", "RESTful Design", "GraphQL Schema", "RPC-based Design"],
    answerIndex: 1,
  },
  {
    id: "cbt1_081",
    tag: "technical",
    prompt: "Which algorithmic complexity grows fastest as data volume increases?",
    options: ["O(n^2)", "O(1)", "O(n)", "O(log n)"],
    answerIndex: 0,
  },
  {
    id: "cbt1_082",
    tag: "technical",
    prompt: "An optimization problem is NP-Complete. What is practical for very large instances?",
    options: ["Binary Search", "Approximation or heuristic algorithms", "Exhaustive search", "Bubble Sort"],
    answerIndex: 1,
  },
  {
    id: "cbt1_083",
    tag: "technical",
    prompt: "Which protocol is commonly used for network device monitoring?",
    options: ["Syslog", "ICMP", "NetFlow", "SNMP"],
    answerIndex: 3,
  },
  {
    id: "cbt1_084",
    tag: "technical",
    prompt: "A scheduler always runs the process with the shortest estimated execution time. Which algorithm is used?",
    options: ["Round Robin", "First Come First Served", "Lottery Scheduling", "Shortest Job First (SJF)"],
    answerIndex: 3,
  },
  {
    id: "cbt1_085",
    tag: "technical",
    prompt: "Which parsing technique naturally handles left-recursive grammars without grammar transformation?",
    options: ["Recursive Descent Parsing", "Predictive Parsing", "LR Parsing", "LL(1) Parsing"],
    answerIndex: 2,
  },
  {
    id: "cbt1_086",
    tag: "technical",
    prompt: "A compiler needs very fast average lookup for millions of identifiers; order is irrelevant. Best choice?",
    options: ["Trie", "B+ Tree", "AVL Tree", "Hash Table"],
    answerIndex: 3,
  },
  {
    id: "cbt1_087",
    tag: "technical",
    prompt: "A key-value store adds and removes servers with minimal key movement. Which technique fits?",
    options: ["Breadth-First Search", "Consistent Hashing", "Dynamic Programming", "Huffman Coding"],
    answerIndex: 1,
  },
  {
    id: "cbt1_088",
    tag: "technical",
    prompt: "Demand paging causes high page faults and low CPU utilization. What should be done first?",
    options: ["Increase Time Quantum", "Reduce Degree of Multiprogramming", "Increase Interrupt Priority", "Disable Virtual Memory"],
    answerIndex: 1,
  },
  {
    id: "cbt1_089",
    tag: "technical",
    prompt: "Threads wait briefly for a very short critical section on multicore hardware. Which primitive is preferred?",
    options: ["Counting Semaphore", "Mutex", "Condition Variable", "Spinlock"],
    answerIndex: 3,
  },
  {
    id: "cbt1_090",
    tag: "technical",
    prompt: "High-priority tasks keep running while low-priority processes wait indefinitely. What issue is this?",
    options: ["Starvation", "Deadlock", "Thrashing", "Fragmentation"],
    answerIndex: 0,
  },
  {
    id: "cbt1_091",
    tag: "technical",
    prompt: "Retries after network failures must not duplicate transaction effects. Which property is required?",
    options: ["Atomicity", "Durability", "Idempotency", "Mutual Exclusion"],
    answerIndex: 2,
  },
  {
    id: "cbt1_092",
    tag: "technical",
    prompt: "A small working set still causes cache misses due to competing blocks mapping together. Which miss is this?",
    options: ["Cold Miss", "Coherence Miss", "Conflict Miss", "Capacity Miss"],
    answerIndex: 2,
  },
  {
    id: "cbt1_093",
    tag: "technical",
    prompt: "A campus network must tolerate a single link failure without isolating other sites. Which topology fits best?",
    options: ["Mesh Topology", "Ring Topology", "Linear Daisy Chain", "Bus Topology"],
    answerIndex: 0,
  },
  {
    id: "cbt1_094",
    tag: "technical",
    prompt: "A variable is used before declaration, but syntax is valid. Which phase reports it?",
    options: ["Code Optimization", "Lexical Analysis", "Semantic Analysis", "Syntax Analysis"],
    answerIndex: 2,
  },
  {
    id: "cbt1_095",
    tag: "technical",
    prompt: "Distributed processes lack synchronized clocks. Which mechanism captures causal event ordering?",
    options: ["Vector Clocks", "CRC Checksum", "Checkpointing", "Consistent Hashing"],
    answerIndex: 0,
  },
  {
    id: "cbt1_096",
    tag: "technical",
    prompt: "A compiler needs machine-independent code for optimization before target generation. What is used?",
    options: ["Intermediate Representation (IR)", "Symbol Table", "Parse Tree", "Object Code"],
    answerIndex: 0,
  },
  {
    id: "cbt1_097",
    tag: "technical",
    prompt: "A compiler removes code unreachable by control flow. Which optimization is used?",
    options: ["Strength Reduction", "Dead Code Elimination", "Loop Fusion", "Constant Folding"],
    answerIndex: 1,
  },
  {
    id: "cbt1_098",
    tag: "technical",
    prompt: "A compiler accepts syntactically invalid programs because its grammar is overly permissive. Which should be corrected first?",
    options: ["Tokenizer", "Grammar specification", "Parser lookahead", "Register allocation"],
    answerIndex: 1,
  },
  {
    id: "cbt1_099",
    tag: "technical",
    prompt: "One core updates a shared cache line; other cores must see the latest value. What ensures this?",
    options: ["Speculative Execution", "Instruction Pipelining", "Cache Coherence Protocol", "Virtual Memory"],
    answerIndex: 2,
  },
  {
    id: "cbt1_100",
    tag: "technical",
    prompt: "A web application experiences sudden traffic spikes. The IT team wants to automatically add servers during peak load and remove them during low usage. Which cloud concept enables this?",
    options: ["Serverless Computing", "Virtual Private Cloud", "Elastic Scaling", "Container Orchestration"],
    answerIndex: 2,
  },
];